- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs:20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install nodejs and mysql packages
  ansible.builtin.dnf:
    name: "{{item}}"
    state: installed
  loop:
  - nodejs
  - mysql

- name: create expense user
  ansible.builtin.user:
    name: expense

- name: Run app-pre-req
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req
    
- name: Install npm dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: Copy file from ansible server to remote server
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: Install python Mysql dependencies
  ansible.builtin.pip:
    name:
    - PyMySQL
    - Cryptography
    executable: pip3.9

- name: Import data into mysql
  community.mysql.mysql_db:
    login_user: "{{ login_user}}"
    login_password: "{{ login_password }}"
    login_host: "{{ login_host }}"
    target: /app/schema/backend.sql
    state: import
    name: all

- name: daemon-reload to pick up configuration changes
  ansible.builtin.systemd_service:
    daemon_reload: yes

- name: Start and enable backend service
  ansible.builtin.service:
    name: backend
    state: started
    enabled: yes
