- name: Install MySql server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Start and enable MySql service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Install Python MySql dependencies
  ansible.builtin.pip:
    name: 
    - PyMySQL
    - Cryptography
    executable: pip3.9
    
# Check Password is already setup or not

- name: Get MySQL version with non-default credentials
  community.mysql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1
    login_host: "{{login_host}}"
    filter: version
  ignore_errors: true
  register: mysql_connection_output

- name: print output
  ansible.builtin.debug:
    msg: "Output: {{mysql_connection_output}}"

- name: Setup root Password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
  when: mysql_connection_output.failed is true