- name: Delete app directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION}}"
    state: absent
  # ignore_errors: true

- name: Create app directory
  ansible.builtin.file:
    path: " {{ APP_LOCATION }}"
    state: directory

- name: Download and extract frontend code
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip
    dest: "{{ APP_LOCATION }}"
  
    
